; required paths/filenames/treenames for input trees
[1]
glob = /d/grid15/serwe/testing/flat_trees/pi0eta__B4_M17_M7/pi0eta.root
tree = pi0eta__B4_M17_M7
num_alt_hypos = 4

[2]
glob = /d/grid15/serwe/testing/flat_trees/gpi0eta__B4/gpi0eta_flat.root
tree = gpi0eta__B4

[3]
glob = /d/grid15/serwe/testing/flat_trees/gpi0eta__B4_M7_M17/gpi0eta_m7_m17_flat.root
tree = gpi0eta__B4_M7_M17

[4]
glob = /d/grid15/serwe/testing/flat_trees/gggg__B4/4gamma_flat.root
tree = gggg__B4

[5]
glob = /d/grid15/serwe/testing/flat_trees/pi0pi0__B4_M7_M7/pi0pi0_flat.root
tree = pi0pi0__B4_M7_M7

; optional configuration
[Misc]
; empty string specifies default output naming convention
outfile = 5_hypo_comparison_big.root
best_per_beam = false
preserve_combos = true
logging = false
